name: eslint

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # setup Node.js
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '14.x'

    # Run scripts
    - name: Install dependencies
      run: yarn install
    - name: linting js files
      run: yarn eslint src/*.js
